name: mdc_web
description: Dart wrapper for the material-components-web javascript library.
version: 0.5.0-pre
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/mdc_web

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.5
  path: ^1.6.2